# This is a basic workflow to help you get started with Actions

name: compile pdf

on:
  push:

jobs:
  buildPython:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - name: update apt-get
        run: apt-get update
      - name: install git
        run: |
          apt-get install -y git
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: install latexmk
        run: |
          wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          zcat < install-tl-unx.tar.gz | tar xf -
          cd install-tl-*
          perl ./install-tl --no-interaction
          echo /usr/local/texlive/2024/bin/x86_64-linux >> $GITHUB_PATH
      - name: install build-essential, python3-dev, python3-full, python3-venv
        run: |
          apt-get install -y build-essential
          apt-get install -y python3-dev
          apt-get install -y python3-full
          apt-get install -y python3-venv
      - name: create venv
        run: python3 -m venv venv
      - name: update pip in venv
        run: |
          . venv/bin/activate
          python3 -m pip install --upgrade pip
      - name: install requirements into venv
        run: |
          . venv/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: First run of making plots (calls twice just to show that they did everything)
        run: |
          . venv/bin/activate
          make fig/fig_intuition.pdf
          make fig/fig_intuition.pdf
          make tikz/fig_intuition/fig_intuition.pdf
          make tikz/fig_intuition/fig_intuition.pdf
          (cd tikz/fig_intuition; latexmk -pdf fig_intuition.tex)
      - name: 'Upload PDFs as artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: compiledFigPDFsInitial
          path: |
            fig/*.pdf
            tikz/fig*/*.pdf
            tikz/fig*/*.fls
            tikz/fig*/*.log
            tikz/fig*/*.fdb_latexmk
            tikz/fig*/*.aux
      - name: Do change, and then rerun
        run: |
          . venv/bin/activate
          make change
          make fig/fig_intuition.pdf
          make fig/fig_intuition.pdf
          make tikz/fig_intuition/fig_intuition.pdf
          (cd tikz/fig_intuition; latexmk -pdf fig_intuition.tex)
      - name: 'Upload PDFs as artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: compiledFigPDFsFinal
          path: |
            fig/*.pdf
            tikz/fig*/*.pdf
            tikz/fig*/*.fls
            tikz/fig*/*.log
            tikz/fig*/*.fdb_latexmk
            tikz/fig*/*.aux
